## tomcat 配置
server:
  ## 监听端口
  port: 9292

## spring 配置
spring:
  ## 动态配置
  profiles:
    active: dev
  ## 邮件配置
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: 854085467@qq.com
    password: ndbkhgbzftqbbbaa
    default-encoding: UTF-8
    test-connection: true
    from: 854085467@qq.com

## mybatis 配置
mybatis-plus:
  ## mapper 文件位置
  mapper-locations: classpath*:com/pearadmin/pro/modules/**/xml/**.xml
  ## domain 实体别名
  type-aliases-package: com.pearadmin

## 分页工具
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


